Add Weixin official account article translator
l0o0/translators_CN pull request #20
Opened 2020-11-20 13:45 UTC by easyteacher

2020-11-27 09:15 UTC, l0o0 commented
同学稍等我检查下，再帮你合并

2020-11-28 12:59 UTC, l0o0 commented on translators/Weixin.js
> +	item.extra = ZU.xpath(doc, "//div[@id='js_content']")[0].innerText.trim().replace(/[\r\n]+/g, "\n");
这里我不建议放到`extra`这个地方，这个内容太多了。建议单独创建一个 note 子条目。可以参考这个代码
```javascript
var noteContent = ZU.xpath(doc, "//div[@id='js_content']")[0].innerText.trim().replace(/[\r\n]+/g, "\n");
var note = '<blockquote>' + ZU.text2html(noteContent) + "</blockquote>";
item.notes.push({note});
```

2020-11-29 02:36 UTC, easyteacher commented on translators/Weixin.js
> +	item.extra = ZU.xpath(doc, "//div[@id='js_content']")[0].innerText.trim().replace(/[\r\n]+/g, "\n");
我需要重新创建Pull request吗，不知道怎么在这上面改

2020-11-29 06:57 UTC, Lemmingh commented
> Add more commits by pushing to the **`master`** branch on **easyteacher/translators_CN**.

👀 这不是你第一次开 PR。按说，堆 commit 已经是常识了。

---

    Pull request := Commit + Collaborate + Review + Merge

2020-11-29 10:30 UTC, Lemmingh commented
再分享一个我写 **JavaScript 脚本**的习惯（module 则是另外一个故事）：

1. 全局常量、全局变量。
2. **入口**。
3. 子模块。

关键是把“入口”放在“子模块”前面。各部分内部的组织较为随意。

这种书写顺序有助于阅读，即使没有注释，也能很快地知道一个脚本的主题，看出它处理问题的大思路。

---

JavaScript 有 hoisting，就是说，在一个 function/global scope 内，`var` 和 `function` 语句无论写在哪个地方，都相当于**声明在整个 scope 的顶部**。它的优点是大多数时候不必关心**声明**的位置；至于缺点，就是 `let` 和 `const` 解决的那些坑，主要是几个反直觉的行为。

2020-11-29 10:30 UTC, Lemmingh requested changes

2020-11-29 10:30 UTC, Lemmingh commented on translators/Weixin.js
> +}
可以考虑把 Open Graph metadata 缓存到个 `Map<string, string>` 里，有时候会比反复访问 DOM 快一点。

不过，如果要加缓存，需要改很多地方。

2020-11-29 10:30 UTC, Lemmingh commented on translators/Weixin.js
> +}
```suggestion
function detectWeb(doc, url) {
    if (doc.title) {
        return "webpage";
    } else {
        return false;
    }
}
```

没明白这个判断的意义：

* “一个已发布的公众号文章的标题为空”应该是件很奇怪的事情。
* 为什么取 OG title，而不是 HTML title？

---

我感觉判 OG type 应该更有意义。**以下是我猜的**，因为我没见过不是文章的公众号文章。

```js
/**
 * @param {Document} doc
 * @param {string} url
 */
function detectWeb(doc, url) {
    /**
     * @type {HTMLMetaElement | null}
     */
    const ogType = doc.head.querySelector('meta[property="og:type"]');

    if (ogType && ogType.content) {
        switch (ogType.content.split(".")[0]) {
            case "article":
                return "document";

            case "video":
                return "videoRecording";

            default:
                return "webpage";
        }
    } else {
        return false;
    }
}
```

不过，那样的话，`doWeb()` 也得跟着改。

2020-11-29 11:44 UTC, easyteacher commented on translators/Weixin.js
> +}
受教了，下周我弄下。

2020-11-29 13:33 UTC, l0o0 commented on translators/Weixin.js
> +}
同学加油呀，感谢@Lemmingh

2021-01-31 08:49 UTC, easyteacher commented
改好了，请查阅。

2021-02-01 02:00 UTC, merged

2023-07-04 13:08 UTC, Huaweidev commented
@easyteacher 目前版本的weixin.js 保存后html文件里的图片无法显示，且保存的html文件体积很小。能看看是什么原因吗？