feat: 支持中国科学院文献情报中心的学位论文
l0o0/translators_CN pull request #49
Opened 2021-10-29 13:14 UTC by with9

感谢您们的贡献.
加入了中科院文献情报学位论文的支持,连接所内网络的时候可以获取学位论文的条目
刚开始学javascript,写的有点暴力.

2021-10-30 05:00 UTC, Lemmingh requested changes
> 写的有点暴力

对自己温柔点，用 [Prettier](https://prettier.io/) 排版。但是，Zotero translator 开头的 metadata 不是 JavaScript，需要手工单独处理。

```json
{
	"arrowParens": "always",
	"endOfLine": "lf",
	"printWidth": 120,
	"semi": true,
	"singleQuote": false,
	"tabWidth": 4,
	"trailingComma": "es5",
	"useTabs": true
}
```

---

此外，这里现在似乎使用 Conventional Commits，所以，请调整 PR 的 title，例如：

```
feat: 支持中国科学院文献情报中心的学位论文
```

---

我只点几处写法上的问题。

2021-10-30 06:46 UTC, with9 commented on translators/dpaper.js
> +		var abstract=doc.evaluate('//span[@id="abstract_cn"]',doc).iterateNext().textContent
谢谢你的批评，我过几天进行修改,目前在忙着开题

2021-10-30 12:30 UTC, with9 commented on translators/dpaper.js
> +		pdfurl=pdfurl.replace(/\'/g,'')
嗯嗯,这里是为了把正则表达式找到的学号部分的单引号给去掉.

2021-10-30 13:47 UTC, with9 commented
感谢您的指导,我稍微修改了下

2021-10-31 07:25 UTC, with9 commented on translators/dpaper.js
> +	var found = false;
这些好像都是zotero生成的模板，我的版本目前用不到这些判断，还没有考虑搜索页面直接获取多个条目，以后会学习着加上，所以现在把这些部分都去掉了

2021-11-01 13:17 UTC, Lemmingh commented
> 我的版本目前用不到这些判断，还没有考虑搜索页面直接获取多个条目，
> 所以现在把这些部分都去掉了

既然如此，不妨考虑：

```javascript
function doWeb(doc, url) {
	const pageType = detectWeb(doc, url);

	switch (pageType) {
		case "thesis":
			scrape({ doc, url, itemType: pageType });
			break;

		default:
			break;
	}
}

function scrape({ doc, url, itemType }) {
	if (itemType === "thesis") {
		const newItem = new Zotero.Item(itemType);

		// ...

		newItem.complete();
	}
}
```

---

```javascript
doc.evaluate('//span[@id="education"]', doc).iterateNext().textContent
```

像这样简单的 [`evaluate()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate) 不妨换成 `querySelector()`。

```javascript
doc.querySelector("span#education").innerText
```

那么，我估计你会打算写：

```javascript
function detectWeb(doc, url) {
	const a = doc.querySelector("span#education");
	if (a && a.innerText.trim()) {
		return "thesis";
	}

	return false;
}
```

---

我注意到连续几次 force-push。不必着急，先想清楚再写码。

---

你在设置 Prettier 时遇到了什么困难吗？

如果使用我上面贴的这个配置文件，结果应当会尽量接近[官方库](https://github.com/zotero/translators)的风格。

```json
{
	"arrowParens": "always",
	"endOfLine": "lf",
	"printWidth": 120,
	"quoteProps": "consistent",
	"semi": true,
	"singleQuote": false,
	"tabWidth": 4,
	"trailingComma": "es5",
	"useTabs": true
}
```

2021-11-01 13:50 UTC, Lemmingh commented
> 尽量接近官方库的风格

解释一下“尽量接近”：

官方库使用大量 ESLint rule 来约束风格。而 Prettier 的特色是 opinionated，它只允许用户设定大方向，而不可以微调每一处细节。

---

另外，现在可以看到 3 条 message 一样的 commit，这容易令人困惑。不妨稍后将它们 squash 成一个。

2021-11-02 11:03 UTC, with9 commented
> > 尽量接近官方库的风格
> 
> 解释一下“尽量接近”：
> 
> 官方库使用大量 ESLint rule 来约束风格。而 Prettier 的特色是 opinionated，它只允许用户设定大方向，而不可以微调每一处细节。
> 
> ---
> 
> 另外，现在可以看到 3 条 message 一样的 commit，这容易令人困惑。不妨稍后将它们 squash 成一个。

恩恩，好的，我一开始用的是vim+zotero的编辑器进行的，后来用了vscode的prettier插件，但是保存的时候会自动格式化，把制表符变成空格,排查一下是另一个插件的原因，禁用之后可以正常的格式化了

恩我也打算没什么大问题的时候，rebase成一个提交

2021-11-02 11:18 UTC, with9 commented
似乎网站进行了修复,没法用这么简单的方式获取下载链接了😂...

2021-11-07 15:18 UTC, Lemmingh commented
> 没法用这么简单的方式获取下载链接了

我这里没有中科院的网络，无法帮你调试。

如果你打算搁置一段时间，可以标记 Draft PR：在右边栏 Reviewers 附近，点击 "Convert to draft"。

---

有几处，你写的不是你想表达的意思。看来，需要讲讲 JavaScript 的奇葩的类型系统。

你学 JavaScript 到什么程度了，<https://javascript.info/> 和 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference) 翻过多少？

能看懂 <https://caniuse.com/> 、 <https://kangax.github.io/compat-table/> 、 <https://node.green/> 等兼容性参考吗？

对前端技术其他部分的了解，比如 [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) 和 [DOM](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API)？

2021-11-08 15:17 UTC, with9 commented
恩恩，好的，我javascript刚开始了解，可以请您举一个我写的和表达的不是一个内容的例子的地方吗

2021-11-21 13:27 UTC, l0o0 commented
@with9 不好意思同学，最近我没怎么关注消息，直到今天才发现。等我有空，我们一起看看

2021-11-28 19:37 UTC, Lemmingh commented
> 举一个我写的和表达的不是一个内容的例子的地方吗

```javascript
a = doc.querySelector("span#education").innerText;
if (a !== null) {
	return "thesis";
}
```

`detectWeb()` 这里很典型，要么第 1 句抛 Error，要么第 2 句恒 `true`。

按我的理解，你本来想说：如果 `span#education` 存在，且它的内容 `innerText` 不是空串，那么，返回 `"thesis"`。

---

我考虑了很久，还是建议你去 <https://javascript.info/>。他们讲课很生动，比我会说话。

之后，看看 `querySelector()` 的定义，再与[我上面提的写法](https://github.com/l0o0/translators_CN/pull/49#issuecomment-956226128)对比，应该就很容易理解了。

2021-11-29 01:57 UTC, l0o0 commented
@with9 同学，别灰心，那个javascript 教程我也在看，哈哈哈

2021-11-29 07:00 UTC, with9 commented
> > 举一个我写的和表达的不是一个内容的例子的地方吗
> 
> ```js
> a = doc.querySelector("span#education").innerText;
> if (a !== null) {
> 	return "thesis";
> }
> ```
> 
> `detectWeb()` 这里很典型，要么第 1 句抛 Error，要么第 2 句恒 `true`。
> 
> 按我的理解，你本来想说：如果 `span#education` 存在，且它的内容 `innerText` 不是空串，那么，返回 `"thesis"`。
> 
> 我考虑了很久，还是建议你去 https://javascript.info/。他们讲课很生动，比我会说话。
> 
> 之后，看看 `querySelector()` 的定义，再与[我上面提的写法](https://github.com/l0o0/translators_CN/pull/49#issuecomment-956226128)对比，应该就很容易理解了。

嗯嗯,好的,谢谢,我去好好学习下, 然后顺便问一下scrape的部分需要确保不会报error吗?

2021-11-29 07:08 UTC, Lemmingh commented
这个大概取决于个人习惯。

如果 `doWeb()` 抛 Error，用户会收到 translator 运行失败的提示。

<https://www.zotero.org/support/dev/translators#recommendations_for_translator_authors>

2021-12-05 16:20 UTC, Lemmingh commented
刚才发现无需登录也可以访问那些 test cases，就进去看了看。😂

他们的代码风格不太行，但逻辑挺清楚。翻出一个接口：

```
http://dpaper.las.ac.cn/Dpaper/detail/detailDoc
```

所以，不需要爬 DOM。

我写了个 proof，你可以在文献页上打开 console 跑。

```javascript
/**
 * @param {string} paperId
 */
const getDetails = async (paperId) => {
    const url = new URL("http://dpaper.las.ac.cn/Dpaper/detail/detailDoc");
    url.searchParams.set("paperID", paperId);
    url.searchParams.set("time", String(new Date().getTime()));
    console.log(url);

    const response = await (await fetch(url.href, { method: "GET" })).json();
    console.log(response);
};

getDetails("20173144");
```

---

至于如何改成 Zotero API，请咨询 @l0o0

2021-12-06 09:14 UTC, Lemmingh commented
> 没法用这么简单的方式获取下载链接了

看上去，`getFile` 需要 5 个参数，但你的第一版只传了 2 个？

---

> scrape的部分需要确保不会报error吗

我现在似乎理解你的意思了。你想问异常处理的推荐实践？没什么特别的，跟其他环境一样：

Only catch exceptions that you **anticipate**.

如果这是你 **预期的、知道如何处理的** 异常，catch；否则，这个异常大概代表某种失误，不要管它，让进程自然崩掉。

---

JavaScript 的 `Error` 给我的印象是鸡肋。尽管现在已经可以较为方便地写 custom Error，还是很少见人拿 Error 做控制流，除了 I/O、`Promise` 等不得不用的地方。

2021-12-06 09:57 UTC, with9 commented
> 看上去，`getFile` 需要 5 个参数，但你的第一版只传了 2 个？

是这样的,一开始他只会在页面点击的时候判断tokens的长度(非中科院研究所长度为1,是中科院但是不同研究所长度为2,只有同研究所长度才是3),如果长度是1或2的话点击全文按钮会提示没有权限.但是只要get请求过去学号和type是可以获得论文的. 

-------

没几天就改成会判断token的值了,现在获取全文需要get三个值(学号,type和token[3])..然后token[3]这个值我不会算.

2021-12-06 10:04 UTC, with9 commented
> 刚才发现无需登录也可以访问那些 test cases，就进去看了看。joy
> 
> 他们的代码风格不太行，但逻辑挺清楚。翻出一个接口：
> 
> ```
> http://dpaper.las.ac.cn/Dpaper/detail/detailDoc
> ```
> 
> 所以，不需要爬 DOM。
> 
> 我写了个 proof，你可以在文献页上打开 console 跑。
> 
> ```js
> /**
>  * @param {string} paperId
>  */
> const getDetails = async (paperId) => {
>     const url = new URL("http://dpaper.las.ac.cn/Dpaper/detail/detailDoc");
>     url.searchParams.set("paperID", paperId);
>     url.searchParams.set("time", String(new Date().getTime()));
>     console.log(url);
> 
>     const response = await (await fetch(url.href, { method: "GET" })).json();
>     console.log(response);
> };
> 
> getDetails("20173144");
> ```
> 
> 至于如何改成 Zotero API，请咨询 @l0o0

好的,谢谢你,我有空看下,最近实验有点忙,还要准备开题😂

2021-12-06 10:20 UTC, Lemmingh commented
![2021-12-06_18-10-40](https://user-images.githubusercontent.com/43396014/144828526-ea58746c-eb10-4837-9454-d6420a1b5c90.png)

`papertitle` 吗？

用 `encodeURIComponent()`，再手拼 URL。

如果里面不会出现空格 (U+0020)，则可以让 `searchParams` 处理。

2021-12-13 02:30 UTC, l0o0 commented
> 如果在Translator 里可以试试这样的代码
```javascript
const paperId = url.match(/paperID=(\d+)/)[1];
const time = String(new Date().getTime());
const getUrl = `http://dpaper.las.ac.cn/Dpaper/detail/detailDoc?paperID=${paperId}&time=${new Date().getTime()}`;
// getUrl.searchParams.set("paperID", paperId);
// getUrl.searchParams.set("time", String(new Date().getTime()));
ZU.doGet(getUrl, function(text) {Z.debug(JSON.parse(text))})
```
上面是在 Translator 中利用接口拉取数据，将把数据转换为 JSON 格式。需要注意 Translator 里还不能使用 await 用法，只能利用回调函数，你可以把生成新 Item 步骤放到回调函数里。然后你可以写一个返回 JSON 字段 与 Item 字段的匹配表
```javascript
const matchFields = {
    title_cn : "title",
    abstract_cn: "abstract"
    ...
}
```
除了一些特殊处理的字段，你都可以遍历这个匹配表，往 Item 中添加字段。万方那个翻译器就是用这样方法。

不过我看这个数据库是不是只有学位论文，简单抓取也是没有问题的。

2021-12-13 06:20 UTC, Lemmingh commented
> Translator 里还不能使用 await

确实，我现在就坐等 Zotero 6。

2022-02-25 11:36 UTC, l0o0 commented
这个翻译器就先合并了

2022-02-27 02:56 UTC, with9 commented
> 这个翻译器就先合并了
嗷嗷,但是下载这个我还是不知道应该怎么搞😂..

2022-02-27 14:02 UTC, l0o0 commented
除了下载附件，其他信息抓取是正常的么？

2022-02-27 14:28 UTC, l0o0 commented
@Lemmingh 别着急，我想着如果正常信息抓取正常，代码能正常运行也是可以的。毕竟大家业余时间写个代码，可能有其他事情影响

2022-02-27 15:04 UTC, l0o0 commented
@Lemmingh 我最近有一个问题，想借这地方咨询下你的意思，毕竟前端相关你也是非常有经验了。因为 Zotero 6 发布在即，插件系统应该也会有变化。旧的 XUL 风格的插件到时大概率要出问题，我在 [zotero-dev group](https://groups.google.com/g/zotero-dev/c/wLZdrPiaKeA/m/PVgi8S93CgAJ) 上询问了，开发者建议使用 bootstrapped 插件，还建议参考使用 [zutilo](https://github.com/wshanks/Zutilo) 插件的写法。

我的问题是，像 Zutilo 的插件，我看仓库中有许多配置文件，这种是使用什么框架或技术来实现的？是使用webpack之类工具么？因为我参考 [scite](https://github.com/scitedotai/scite-zotero-plugin) 插件，其仓库中有webpack的配置文件。或许webpack 是一个好的工具，我可以用来改造现有的插件，也可能为后面新的特性添加可能性。按你的开发经验，有没有相关的webpack学习路线图或相关的文档可以参考呢？

2022-02-28 10:04 UTC, with9 commented
> 除了下载附件，其他信息抓取是正常的么？

嗯嗯,其他信息抓取是正常的

2022-04-02 07:49 UTC, merged